// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn67GaIJ_OEA31laXwFdHg1pmmNk1k_10',
    appId: '1:502256906180:web:b6e593b3b5f5c795893e91',
    messagingSenderId: '502256906180',
    projectId: 'firsttest-ffdbd',
    authDomain: 'firsttest-ffdbd.firebaseapp.com',
    storageBucket: 'firsttest-ffdbd.appspot.com',
    measurementId: 'G-K2KP0MP3YJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVMAdCy_1FJHIbqPYk3iQUvfkkSH5DuJE',
    appId: '1:502256906180:android:ffb0d62855d23224893e91',
    messagingSenderId: '502256906180',
    projectId: 'firsttest-ffdbd',
    storageBucket: 'firsttest-ffdbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD37BEP11Y6qyNYcn2itFzHbagHKyDrCQ',
    appId: '1:502256906180:ios:96fb1b089d0388f1893e91',
    messagingSenderId: '502256906180',
    projectId: 'firsttest-ffdbd',
    storageBucket: 'firsttest-ffdbd.appspot.com',
    iosBundleId: 'com.example.flutter1st',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD37BEP11Y6qyNYcn2itFzHbagHKyDrCQ',
    appId: '1:502256906180:ios:96fb1b089d0388f1893e91',
    messagingSenderId: '502256906180',
    projectId: 'firsttest-ffdbd',
    storageBucket: 'firsttest-ffdbd.appspot.com',
    iosBundleId: 'com.example.flutter1st',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn67GaIJ_OEA31laXwFdHg1pmmNk1k_10',
    appId: '1:502256906180:web:b6e593b3b5f5c795893e91',
    messagingSenderId: '502256906180',
    projectId: 'firsttest-ffdbd',
    authDomain: 'firsttest-ffdbd.firebaseapp.com',
    storageBucket: 'firsttest-ffdbd.appspot.com',
    measurementId: 'G-K2KP0MP3YJ',
  );

}